### PR TITLE
Use the anaconda compilers on osx and linux

### PR DESCRIPTION
**Pull request by jeanconn**
Use the anaconda compilers on osx and linux

My understanding is that the anaconda clang on OSX will need access to an SDK and is configured by default to use /opt/MacOSX10.9.sdk.  I haven't figured out how to use a different one or how to get it to respect MACOSX_DEPLOYMENT_TARGET and CONDA_BUILD_SYSROOT . 

It also looks to me like if /opt/MacOSX10.9.sdk isn't present but there is an SDK installed in /Library from Xcode, the anaconda clang seems to work with that without error.

### CODE REVIEW

**Comment by taldcroft** [comment]
I'm trying this out, but it needs to be rebased on current shiny to work e.g. with `python ska_builder.py --force --tag shiny Chandra.Time`.

**Comment by taldcroft** [comment]
Is there something for Windows?

**Comment by jeanconn** [comment]
Why does it need rebase?

**Comment by jeanconn** [comment]
And as far as I can tell there is nothing for Windows.  https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html

**Comment by jeanconn** [comment]
But it looks like conda-forge may be building packages for windows with 'vs2015', so that might just be more recent than the anaconda 5 compiler notes in the conda-build documentation.  And maybe it would just work with the {{ compiler('c') }} etcsyntax.

**Comment by taldcroft** [comment]
> Why does it need rebase?

It wasn't working with --repo-url.  :frowning:

**Comment by taldcroft** [comment]
On Windows, that's fine, I was just checking for completeness.

**Pull request merged**
