### PR TITLE
Make ska3-matlab metapackage

### PR DESCRIPTION
**Pull request by jeanconn**
Make a ska3-matlab metapackage.  This starts from ska3-flight 2018.12.18 plus some anticipated bugfixes.

### CODE REVIEW

**Comment by jeanconn** [comment]
Sure seems like ska3-flight 2018.12.18 is fine if you want to match what is installed right now on GRETA (IIRC, haven't logged in over there today to check).

Anyway, with regard to keeping ska3/matlab32 up-to-date, I assume that ska3/matlab32 should get replaced to match the directory structure on GRETA, but there were a few other things going on at the time.

**Comment by jeanconn** [comment]
IIRC I also gave up on trying to test the environment on HEAD and moved to just testing on GRETA; but if you think there's still value in using quango as a proxy for their machines that's fine.

**Comment by jeanconn** [comment]
PS With regard to ska3/matlab being ancient... I think it is only outdated by 5 Jean-in-the-office days :smile:.

**Comment by taldcroft** [comment]
Good point about using GRETA as the test platform 32-bit since it is really the only target.  And with that we could perhaps just not have /proj/sot/ska3/matlab32 on HEAD.  From my perspective better to not have it all than potentially be incorrect.

I put some new details in the [package developer process](https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-maintainers#package-developer-process).

**Pull request merged**
