### PR TITLE
WIP: ska3-prime

### PR DESCRIPTION
**Pull request by javierggt**
These are changes to update core packages. It uses python 3.10. The process to make this is roughly described in [the wiki](https://github.com/sot/skare3/wiki/Updating-the-Core-Conda-Packages).

To install:
```
conda create -n ska3-flight-2023.0rc4 --override-channels \
  -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/prime \
  ska3-flight==2023.0rc4
```

This is work in progress, these are some of the known issues:
- ska3-perl is not updated
- does not include windows updates
- It fixes most issues about [updating externals](https://github.com/sot/skare3/issues?q=is%3Aissue+is%3Aopen+label%3A%22Package+update%22+label%3Aexternals)
  - coverage is missing
- does not fix the following issues (it should):
   - #969
   - #967 
 
the process has these issues that I had to solve manually:
 - fails to fetch the right quaternion package.
 - the process installs pyqt5-sip from the `pypi` platform.
 - the resulting ska3-flight does not include ska3-core as dependency.

I ran tests:
- HEAD: [dashboard](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/ska3-prime-2023.0rc4-HEAD/) | [log](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/ska3-prime-2023.0rc4-HEAD/ska3-prime.log)
- Mac OS: [dashboard](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/ska3-prime-2023.0rc4-OSX/) | [log](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/ska3-prime-2023.0rc4-OSX/ska3-prime.log)

### CODE REVIEW

**Comment by jeanconn** [comment]
I've been fiddling with this on linux with the starcheck use case.  I just ran into `jplephem` is missing on the Python side.

**Comment by jeanconn** [comment]
Oh, that's probably because ska3-core isn't a dependence.   I'll try that.

**Comment by jeanconn** [comment]
Do we still need this PR @javierggt? or is this superseded by #1008 ?

**Comment by javierggt** [comment]
I used this branch to make the 2023.1 branch. Should not be needed anymore.

**Pull request closed without merging**
