### PR TITLE
Remove more unused and deprecated dependencies from recipes

### PR DESCRIPTION
**Pull request by jeanconn**
Remove more unused and deprecated dependencies from recipes

### CODE REVIEW

**Review by javierggt — APPROVED** [review]
Looks fine by me, especially considering we do not care much about these dependencies.

Strictly speaking, if we list the dependencies then chandra_time would be replaced by cxotime, and the others?

**Comment by jeanconn** [comment]
Right, but I checked acis_thermal_check, for example, and it still had calls to Chandra.Time, so I left it alone.

**Comment by javierggt** [comment]
> I checked acis_thermal_check, for example, and it still had calls to Chandra.Time, so I left it alone

what do you mean? you removed the dependency from acis_thermal_check, and I think that's fine: I searched and I did see any use of Chandra.Time. So we might be talking of two different things :-)

**Comment by jeanconn** [comment]
Sorry, yeah, it was the other way.. with chandra_time calls in the kadi code.

**Pull request merged**
