### PR TITLE
Collection of updates for starcheck + chandra_aca + agasc 

### PR DESCRIPTION
**Pull request by jeanconn**
Updates to chandra_aca, agasc, xija
Inclusion of starcheck and a more rigorous ska3-perl metapackage.

### `chandra_aca` 4.24

- [Infrastructure improvements to transform module](https://github.com/sot/chandra_aca/pull/66)
- [Add new grid model infrastructure and 2018-11 acq prob model](https://github.com/sot/chandra_aca/pull/65)

### `agasc` 4.7

- [Include near neighbor stars and exclude rarely used cols from miniagasc](https://github.com/sot/agasc/pull/36)
- [Update COLOR1 column to reflect AGASC 1.7 mag updates](https://github.com/sot/agasc/pull/37)

### `xija` 4.13

- Release 4.13 with step function power input from xija 3.12 (already in Ska2) and new Qt gui_fit now in 4.13

### `kadi` 3.16.3

- [Remove unused 'check' blocks in cmds task_schedules](https://github.com/sot/kadi/pull/121)
- [Do event updates on a local copy and move back](https://github.com/sot/kadi/pull/124)

### `Ska.engarchive` 4.44

- [Make update_archive.py module py3-compatible](https://github.com/sot/eng_archive/pull/143)

### `proseco` 4.2

- Updates to support include/exclude lists of stars for acq and guide
- Update to support more reasonable mag err limits for color=1.5 stars
- Update to support use of grid-acq probabilities from chandra_aca 4.24 

### `starcheck` 12.1

- Ska3 version of starcheck with -9.5C planning limit and pre-safe-mode probability thresholds

### CODE REVIEW

**Comment by jeanconn** [comment]
Though I thought everything in "Infrastructure improvements to transform module" was in "Add new grid model infrastructure and 2018-11 acq prob model".

**Comment by jeanconn** [comment]
I'm running into the little hiccup that, for reasons I cannot explain, installing ska3-flight now (and previous to this, apparently) wants to install perl etc.  Do we care?  If we care, I think the most direct way to fix this would be to put the packages from skare3-static in their own conda repo and add to .condarc when you want Perl.

I've tried looking at this in the conda debugging, but the package solver mentions nothing about the perl packages until the end, when it adds them to the list to install.  I think this might be a bug in our ancient version of conda.

**Comment by jeanconn** [comment]
Not sure if I should continue to wait on annie.  Also not sure if I the working guide star include/exclude in proseco should drive a 4.2 that gets in here.  A little concerned the week is half gone.

**Comment by taldcroft** [comment]
I don't think annie or proseco are blockers here.  The hope with skare3 is that updating packages will be really easy so it can just slide to next week.  Sound about right?

**Comment by jeanconn** [comment]
Sounds good.  I just didn't want to cut things @taldcroft put in the PR text at the top without discussion, as I was considering them soft liens.

**Comment by jeanconn** [comment]
Though not sure if we want to cut another proseco now or wait.  

Overall, updating packages is not a big deal, but I haven't figured out our minimum requirements for testing (does everything need to be integration tested in a test environment on all platforms?) and the level of detail needed for getting approval / briefing the community.

**Pull request merged**
