### PR TITLE
Add python-pptx recipe and add it to ska3-core on linux64

### PR DESCRIPTION
**Pull request by jeanconn**
Add python-pptx recipe and add it to ska3-core on linux64

### CODE REVIEW

**Comment by taldcroft** [comment]
For the record can you remind me where to find the build recipe?  I can find everything but that on conda-forge.

**Comment by jeanconn** [comment]
There is no one place.  For this package that has a conda-forge recipe, I just stole and modified from https://github.com/conda-forge/python-pptx-feedstock/blob/master/recipe/meta.yaml

**Comment by taldcroft** [comment]
And how did you discover that, and what is your general discovery process.  All this should go into the maintainer docs so we aren't single strung on all the conda stuff.

**Comment by jeanconn** [comment]
My approach was to google.  But that seems poor for the docs :smile: .

**Comment by jeanconn** [comment]
I think we decided against including this package in ska3-flight, but I'm not sure if there is value in just merging the recipe (per the approval).

**Comment by jeanconn** [comment]
I wouldn't want to merge the update to ska3-core.

**Comment by taldcroft** [comment]
Agreed to merge the recipe but take it out of ska3-core.  I am not sure why I approved this, maybe didn't appreciate the inclusion in ska3-core when I clicked approve.

**Pull request closed without merging**
