### PR TITLE
change chandra_aca build requirement to include astropy

### PR DESCRIPTION
**Pull request by javierggt**

### CODE REVIEW

**Comment by taldcroft** [comment]
I realize now this could be (maybe *should* be) done with requests instead of astropy.  I just had that code from the original version when it was being done in the user code not setup.py. Probably doesn't matter, but requests is a much lighter dependency.

**Comment by taldcroft** [comment]
But certainly we can run with this for now.

**Comment by javierggt** [comment]
well, the chandra_aca is failing anywya, and I have never seen that... I'll have lunch and try again in about half hour.

**Comment by javierggt** [comment]
so it might still be a good idea to change the dependency.

**Pull request merged**
