### PR TITLE
Add jobwatch

### PR DESCRIPTION
**Pull request by jeanconn**
Add jobwatch

### CODE REVIEW

**Comment by javierggt** [comment]
fine by me.

**Comment by javierggt** [comment]
I can remove the one I added in the release branch, since this might be better. Also, mine does not work.

The package is arch-dependent?

**Comment by jeanconn** [comment]
It has a couple of entry-point scripts so I think that makes it arch-dependent.

**Comment by javierggt** [comment]
ok, let's merge 😄

**Pull request merged**
