### PR TITLE
WIP: Add skare3 recipes to build django 3.0.1 and deps

### PR DESCRIPTION
**Pull request by jeanconn**
Add skare3 recipes to build django 3.0.1 and deps

### CODE REVIEW

**Comment by jeanconn** [comment]
I think just building our own is less problematic than trying to use conda package made with more modern conda versions.

**Comment by taldcroft** [comment]
This is just killing me.  Can you indulge me and show what happens otherwise?

**Comment by jeanconn** [comment]
What is the alternate path?  Grab the sqlparse, asgiref, django from modern repository?  I am concerned that any path isn't the same as your pip install which was what was tested.

**Comment by taldcroft** [comment]
Yes, try grabbing those packages from modern repo and see if it works.  I don't know what you mean by "any path".  These are all three pure Python packages, so it seems quite possible things will just work??

**Comment by jeanconn** [comment]
By "any path" I meant any non-pip way of getting these files into our environment.

And sure, I think I had previously run into the issue that modern packages didn't work for our conda at all (and you had those examples of weird checksum fails) so I figured these borrowed recipes would actually save some time, but fine to try.

**Comment by jeanconn** [comment]
Do you have recommended ways to test out the django installation besides running kadi?

**Comment by jeanconn** [comment]
It didn't die on installation and seems to import, so maybe you are right and the conda-forge linux-64 py36_0 package I grabbed won't be a disaster.  🤞

**Comment by taldcroft** [comment]
For django testing it appears there is no `django.test()`, so testing with kadi is the only thing I can think of.  In practice it is also the only thing that really matters.

**Comment by jeanconn** [comment]
Thanks!, and yes, I'd looked for django.test and any django internal recommendations and didn't see them.  It looks like it is working.  With regard to the "only thing that matters" I figured that the web server would use the same conda package, but if we run into a new fail in that testing we can address then.

I'm not sure about the best place to capture/document that the asgiref, sqlparse, and django conda packages are the ones that I retrieved from conda-forge.

**Comment by jeanconn** [comment]
@taldcroft Oops.  I forgot to go and check this for 32bit.   I can't find built packages at the right version (I know you keep saying Django isn't really a binary package but not sure if we want to pip install in the ska3/matlab conda environment or make our own conda package.)

**Comment by taldcroft** [comment]
Yes, I don't understand why django packages are separated by arch on conda but not on PyPI.  Anyway, looks like there is no choice but rolling our own, again..  Sigh.

**Pull request closed without merging**
