### PR TITLE
Flight 2019.11.15

### PR DESCRIPTION
**Pull request by jeanconn**
Updates to ska3-flight for 2019.11.15

### CODE REVIEW

**Comment by javierggt** [comment]
I suppose this is a pertinent place to ask the following question: What about issues #90 and #205?

I am not clear why we would not include starcheck 13.5 (#205).

Issue #90 (remove nbpresent from ska3-core) has been there for a year. What's the deal with that?

**Comment by jeanconn** [comment]
This is a fine place to put it or I could update the issues if they need to be statused on github (and we didn't status them in our tagup).

We want to do #90, but when I tried last (by just cutting it from ska3-core) the dependencies didn't work, and conda dependency management tried to remove *other* packages we actually did actually want.  I haven't had a chance to look at that in more detail.

Regarding #205 in starcheck, I had two open pull requests, one with an open review request.  Overall, I thought we might as well wait to get more merged into master in there before cutting a starcheck release.

**Comment by jeanconn** [comment]
These changes were approved at LR today.

**Comment by jeanconn** [comment]
OK.  So remaining actions for this release:

 - [ ] build ska3-flight conda package as aca user on presto from ska3 build environment (could be done first or after then next two steps)
 - [ ] merge this PR
 - [ ] Make a github release for skare3 2019.11.15 
 - [ ] wait for approval of NOV1819A products
 - [ ] copy ska3-flight conda package into /proj/sot/ska/www/ASPECT_ICXC/ska3-conda/noarch
 - [ ] run conda index on that noarch dir
 - [ ] as aca user on presto in a new shell get into ska3 flight conda environment and update ska3-flight in the environment
 - [ ] as SOT user on cheru and chimchim update ska3 flight environments similarly
 - [ ] run ska_testr tests and review outputs

**Pull request merged**
