### PR TITLE
Add env vars for HEAD Sybase mica test

### PR DESCRIPTION
**Pull request by jeanconn**
Add env vars for HEAD Sybase mica test

### CODE REVIEW

**Comment by jeanconn** [comment]
@javierggt if you don't want to source into a ska environment with ska_envs.sh, maybe we could just set these vars to let the mica report test run in your HEAD test environment?

**Comment by javierggt** [comment]
I think this `LD_LIBRARY_PATH` gets ignored in the environment.

I tried this once and it did not work, possibly because I still had no access. We can try again, but when I try, I need to remind myself how is LD_LIBRARY_PATH set (and document it somewhere).

**Comment by jeanconn** [comment]
IIRC setting the variable worked for me in a local test, but I didn't have a good way to test it with the workflow.

**Comment by jeanconn** [comment]
I still thought this would probably work but am now confused about what permissions the runner has.

**Review by javierggt — APPROVED** [review]
I created a [test workflow](https://github.com/sot/skare3/runs/2796698431?check_suite_focus=true) that defines these environmental variables, and test_get_rms_data passes. It seems to work, so I say we merge this.

Just keep in mind that the environment of the runner was one of the things I struggled a bit when setting things up, and I have not repeated it. I should do that soon, so it is documented precisely.

**Pull request merged**
