### PR TITLE
Add fot_matlab module

### PR DESCRIPTION
**Pull request by jeanconn**
Add fot_matlab Python package as a fot-matlab conda package.

### CODE REVIEW

**Comment by jeanconn** [comment]
This isn't working for me yet with ska_builder, so still a wip.

**Comment by jeanconn** [comment]
I just don't know if we want this a conda package fot-matlab or fot_matlab . Makes no nevermind to me.

**Comment by javierggt** [comment]
fot-matlab

**Comment by jeanconn** [comment]
OK I renamed the pieces that were fot_matlab to fot-matlab .  Not knowing the storied history of modules with dashes instead of underscores, I thought it was just a typo to have the dash in the name before, but if it is liked that is fine.

**Comment by jeanconn** [comment]
I'll wait to merge until this has had a review.

**Comment by javierggt** [comment]
Does this package define any scripts? It does not seem like it. Does it have any platform dependent component?

If the answer to both of these is no, then this should be a noarch package:
```
build:
  noarch: python
```

**Comment by jeanconn** [comment]
Sure.  I suppose I was half thinking that with your automated build system noarch packages didn't buy us anything except a problem later when a script or task_schedule or some such gets added and then we can't remember why it doesn't work!

**Review by javierggt — APPROVED** [review]

**Comment by javierggt** [comment]
well, I guess you are right about that last point.

**Comment by javierggt** [comment]
it's just that when I added the workflow, I was half thinking it would be noarch :-) the two need to agree.

**Comment by jeanconn** [comment]
Sounds good.

**Pull request merged**
