### PR TITLE
Update default ska_builder python and numpy versions

### PR DESCRIPTION
**Pull request by jeanconn**
Update default ska_builder python to 3.10 and numpy to 1.21

I think this is only used when building manually.

### CODE REVIEW

**Comment by javierggt** [comment]
Good point. Now that you mention it... the numpy version should be changed to.

For reference, the current build workflow specify them explicitly: https://github.com/sot/skare3/blob/master/.github/workflows/package_build.yml

The numpy version there is 1.21

**Comment by jeanconn** [comment]
Ah.  OK I'll update numpy too.  Though that makes me wonder if we should have the script and the workflow both read from something in the repo.

**Comment by javierggt** [comment]
That complicates the workflow. I would leave it.

**Comment by jeanconn** [comment]
OK.  I just updated the numpy version too for this.

**Review by javierggt — APPROVED** [review]

**Pull request merged**
