### PR TITLE
Shiny ska3 perl latest

### PR DESCRIPTION
**Pull request by taldcroft**
The analogy to ska3-flight-latest and ska3-core-latest.

### CODE REVIEW

**Comment by jeanconn** [comment]
I was figuring the libuuid thing would not be an issue requiring a pin in the metapackage because mostly conda-forge won't be in channels?  But I suppose ska3-perl-latest has a small enough user base (us) that it doesn't matter.

**Comment by taldcroft** [comment]
It's needed to make the original process of assembling the packages (starting from scratch) reproducible / deterministic.

**Comment by jeanconn** [comment]
OK. So does this replace the conda install package set in my build process or update a secondary process?

**Comment by taldcroft** [comment]
Yes, this replaces the long command-line list and is the "latest" analog to the existing `ska3-perl` package. So now `conda create -n ska3-shiny -c ... ska3-core-latest ska3-flight-latest ska3-perl-latest`.

BTW did you ever file an issue with conda on the problem in the defaults perl package? Maybe they can just fix that!

**Pull request merged**
