### PR TITLE
Update xija to 4.14 in ska3-matlab

### PR DESCRIPTION
**Pull request by jeanconn**
Update xija to 4.14 in ska3-matlab

This includes the ska3-core update to install astropy-healpix.

### CODE REVIEW

**Comment by jeanconn** [comment]
Will a version of acis_taco need to be cut and installed too?

**Comment by jeanconn** [comment]
This is built in the test channel as-is now.

**Comment by mbaski** [comment]
@jeanconn - do you want sparkles 4.2 to be part of the package updates for the MATLAB Tools release we're about to start testing (i.e do I need to add it to the Windows build?)

**Comment by jeanconn** [comment]
Thanks Mark.  I think it is benign enough and helpful enough that it can go in in this release (and the Windows build), but I was going to do some more integration tests today before pinging you.

**Comment by mbaski** [comment]
Sounds good, I'll wait to you give the go ahead.

**Comment by jeanconn** [comment]
Hi Mark.  Integration testing found one tiny test issue which Tom fixed.  We are good to go with sparkles at [4.2.1](https://github.com/sot/sparkles/releases/tag/4.2.1).

**Comment by mbaski** [comment]
Thanks Jean, I'll get it into the Windows build.

**Comment by jeanconn** [comment]
@mbaski  I've just added proseco 4.5 https://github.com/sot/proseco/releases/tag/4.5 to  this pull request for the updated environment for 2019_158 .

**Comment by mbaski** [comment]
Thanks Jean, I installed it in the Windows area.

**Comment by jeanconn** [comment]
Approved by FMTCB FDB and FD on 21-Jun-2019.

**Pull request merged**
