### PR TITLE
Release 2020.6

### LINKED ISSUE #353: Update package ska_helpers to 0.1.1
Update package ska_helpers to version 0.1.1

Includes the following merges:
- PR #10: when running testr, avoid emitting this warning
- PR #9: Setting up automated builds

### LINKED ISSUE #354: Update sot/Chandra.Maneuver to 3.7.3
PR #16: Make namespace package native
PR #17: Setting up automated builds

Includes the following merges:
- PR #16: Make namespace package native
- PR #17: Setting up automated builds

### LINKED ISSUE #355: Update sot/Chandra.Time to 3.20.6
Includes the following merges:
- PR #39: Fix the location of the C extension

### LINKED ISSUE #356: Update sot/cmd_states to 3.15.2
PR #48: Make namespace package native
PR #49: Setting up automated builds

Includes the following merges:
- PR #48: Make namespace package native
- PR #49: Setting up automated builds

### LINKED ISSUE #357: Update sot/eng_archive to 4.48.0
PR #193: Add MSID title and unit y-label to plot
PR #191: Add code to support and test computed MSIDs
PR #188: Allow a fixed number of sync dirs instead of removing by date
PR #190: Setting up automated builds
PR #189 Make namespace package native

Includes the following merges:
- PR #189: Make namespace package native
- PR #193: Add MSID title and unit y-label to plot
- PR #191: Add code to support and test computed MSIDs
- PR #188: Allow a fixed number of sync dirs instead of removing by date
- PR #190: Setting up automated builds

### LINKED ISSUE #358: Update sot/kadi to 5.1.0
PR #161: Add acisfp_setpoint state
PR #162: Improve get_cmds_from_backstop
PR #159: Fix test to run on Windows

Includes the following merges:
- PR #161: Add acisfp_setpoint state
- PR #162: Improve get_cmds_from_backstop
- PR #159: Fix test to run on Windows

### LINKED ISSUE #359: Update sot/Ska.arc5gl to 3.1.4
PR #8: Setting up automated builds
PR #7 Make namespace package native

Includes the following merges:
- PR #7: Make namespace package native
- PR #8: Setting up automated builds

### LINKED ISSUE #360: Update sot/Ska.astro to 3.2.4
PR #8: Setting up automated builds
PR #7 Make namespace package native

Includes the following merges:
- PR #7: Make namespace package native
- PR #8: Setting up automated builds

### LINKED ISSUE #361: Update sot/Ska.DBI to 4.0.2
PR #14: Make namespace package native
PR #16: Fix / improve tests to run on Windows
PR #15: Setting up automated builds

Includes the following merges:
- PR #14: Make namespace package native
- PR #16: Fix / improve tests to run on Windows
- PR #15: Setting up automated builds

### LINKED ISSUE #362: Update sot/Ska.File to 3.4.4
PR #8: Make namespace package native
PR #9: Setting up automated builds

Includes the following merges:
- PR #8: Make namespace package native
- PR #9: Setting up automated builds

### LINKED ISSUE #363: Update sot/Ska.ftp to 3.5.3
PR #18: Make namespace package native
PR #20: Windows compatibility
PR #19: Setting up automated builds

Includes the following merges:
- PR #18: Make namespace package native
- PR #20: Windows compatibility
- PR #19: Setting up automated builds

### LINKED ISSUE #364: Update sot/Ska.Matplotlib to 3.11.4
PR #11: Make namespace package native
PR #12: Setting up automated builds

Includes the following merges:
- PR #11: Make namespace package native
- PR #12: Setting up automated builds

### LINKED ISSUE #365: Update sot/Ska.Numpy to 3.8.4
Includes the following merges:
- PR #6: Fix the location of the C extension

### LINKED ISSUE #366: Update sot/Ska.ParseCM to 3.3.4
PR#6: Make namespace package native
PR#7: Setting up automated builds

Includes the following merges:
- PR #6: Make namespace package native
- PR #7: Setting up automated builds

### LINKED ISSUE #367: Update sot/Ska.quatutil to 3.3.3
PR #8: Make namespace package native
PR #9: Setting up automated builds

Includes the following merges:
- PR #8: Make namespace package native
- PR #9: Setting up automated builds

### LINKED ISSUE #368: Update sot/Ska.Shell to 3.4.1
PR #16: Make namespace package native
PR #18: Skip all tests on Windows
PR #17: Setting up automated builds

Includes the following merges:
- PR #16: Make namespace package native
- PR #18: Skip all tests on Windows
- PR #17: Setting up automated builds

### LINKED ISSUE #369: Update sot/Ska.Sun to 3.5.3
PR #10: Make namespace package native
PR #11: Setting up automated builds

Includes the following merges:
- PR #10: Make namespace package native
- PR #11: Setting up automated builds

### LINKED ISSUE #370: Update sot/Ska.tdb to 3.5.3
PR #10: Make namespace package native
PR #11: Setting up automated builds

Includes the following merges:
- PR #10: Make namespace package native
- PR #11: Setting up automated builds

### LINKED ISSUE #371: Release 2020.6
Release of ska3-flight 

# Packages to include

- acis_thermal_check 3.1.0
- ska_helpers 0.1.1
- kadi 5.2.0
- mica 4.21.2
- maude 3.3.2
- Chandra.Maneuver 3.7.3
- Chandra.Time 3.20.6
- cmd_states 3.15.2
- eng_archive 4.48.0
- Ska.arc5gl 3.1.4
- Ska.astro 3.2.4
- Ska.DBI 4.0.2
- Ska.File 3.4.4
- Ska.ftp 3.5.3
- Ska.Matplotlib 3.11.4
- Ska.Numpy 3.8.4
- Ska.ParseCM 3.3.4
- Ska.quatutil 3.3.3
- Ska.Shell 3.4.1
- Ska.Sun 3.5.3
- Ska.tdb 3.5.3
- starcheck 13.6.0

# Checklist

- [x] Document all changes
- [x] Build all packages
   - [x] noarch
   - [x] linux 64
   - [x] mac 64
- [x] Copy Packages to test channel
- [x] Document test status
- [x] Get approval
- [x] Move individual packages to main conda channel
- [ ] Update production systems:
   - [x] announce to aca@cfa
   - [x] move ska3-flight package to main conda channel
   - [x] update HEAD ska3/flight as aca user
   - [ ] run ska_testr on HEAD
   - [ ] update ska3/flight on cheru as sot user
   - [ ] update ska3/flight on chimchim as SOT user
   - [ ] announce to chandracode and mpweekly

### LINKED ISSUE #375: Update package starcheck to 13.6.0
Update package starcheck to version 13.6.0

Includes the following merges:
- List PR merges

### LINKED ISSUE #376: Update package kadi to 5.2.0
Update package kadi to version 5.2.0 

Includes the following merges:
- List PR merges

### LINKED ISSUE #377: Update package maude to 3.3.2
Update package maude to 3.3.2

Includes the following merges:
- PR sot/maude/issues/21: Update regression test to reflect new MAUDE FLIGHT processing
- PR sot/maude/issues/20: Setting up automated builds

### LINKED ISSUE #381: Update sot/mica to Release 4.21.2
Includes the following merges:
- PR #223: Use github token authentication in workflow
- PR #222: Change sybase skip test to check for more restrictive vv creds
- PR #221: Recast dark cal image to native byte order

### PR DESCRIPTION
**Pull request by javierggt**
# ska3-flight 2020.6

## Summary:
The ska3-flight 2020.6 release includes:
   * starcheck updates to
      * work better with the April ACA CCD limit increase
      * support RLTT and schedule stop
   * kadi commands-related updates to
      * support the starcheck RLTT and schedule stop change
      * add support for ACIS FP state
   * eng_archive update to support computed msids
   * Ska and Chandra are now "native namespace packages". This is a purely technical change that makes maintenance easier. 
   * Documentation for acis_thermal_check

## Interface Impacts:
   * None
## Testing:
   * Standard suite of regression tests was run on HEAD (summary below)
   * One Ska.engarchive test fails. This test was reported failing in the previous release, so here we note again: this test failure is a known and non-impacting issue with the sync process / sync test.
## Review:
   * PRs (see changes below) have been reviewed by the ACA team.
## Deployment:
   *  The 2020.6 ska3-flight release will be deployed on HEAD and GRETA ska3/flight after the release and products for the week are approved.
# Code changes

## ska3-flight (2020.5 -> 2020.6rc3)

**acisops/acis_thermal_check:** 3.0.0 -> 3.1.0 (3.0.0 -> 3.1.0)
  - [PR 27](https://github.com/acisops/acis_thermal_check/pull/27): Documentation for acis_thermal_check

**sot/Chandra.Maneuver:** 3.7.2 -> 3.7.3 (3.7.2 -> 3.7.3)
  - [PR 17](https://github.com/sot/Chandra.Maneuver/pull/17): Setting up automated builds
  - [PR 16](https://github.com/sot/Chandra.Maneuver/pull/16): Make namespace package native

**sot/Chandra.Time:** 3.20.4 -> 3.20.6 (3.20.4 -> 3.20.5 -> 3.20.6)
  - [PR 38](https://github.com/sot/Chandra.Time/pull/38): Setting up automated builds
  - [PR 37](https://github.com/sot/Chandra.Time/pull/37): Make namespace package native
  - [PR 39](https://github.com/sot/Chandra.Time/pull/39): Fix the location of the C extension

**sot/cmd_states:** 3.15.1 -> 3.15.2 (3.15.1 -> 3.15.2)
  - [PR 49](https://github.com/sot/cmd_states/pull/49): Setting up automated builds
  - [PR 48](https://github.com/sot/cmd_states/pull/48): Make namespace package native

**sot/eng_archive:** 4.47.4 -> 4.48.0 (4.47.4 -> 4.48.0)
  - [PR 190](https://github.com/sot/eng_archive/pull/190): Setting up automated builds
  - [PR 188](https://github.com/sot/eng_archive/pull/188): Allow a fixed number of sync dirs instead of removing by date
  - [PR 191](https://github.com/sot/eng_archive/pull/191): Add code to support and test computed MSIDs
  - [PR 193](https://github.com/sot/eng_archive/pull/193): Add MSID title and unit y-label to plot
  - [PR 189](https://github.com/sot/eng_archive/pull/189): Make namespace package native

**sot/kadi:** 5.0.1 -> 5.2.0 (5.0.1 -> 5.1.0 -> 5.2.0)
  - [PR 159](https://github.com/sot/kadi/pull/159): Fix test to run on Windows
  - [PR 162](https://github.com/sot/kadi/pull/162): Improve get_cmds_from_backstop
  - [PR 161](https://github.com/sot/kadi/pull/161): Add acisfp_setpoint state
  - [PR 163](https://github.com/sot/kadi/pull/163): Add inclusive_stop kwarg to get_cmds
  - [PR 164](https://github.com/sot/kadi/pull/164): Allow start and stop in get_states() with cmds

**sot/maude:** 3.3.1 -> 3.3.2 (3.3.1 -> 3.3.2)
  - [PR 20](https://github.com/sot/maude/pull/20): Setting up automated builds
  - [PR 21](https://github.com/sot/maude/pull/21): Update regression test to reflect new MAUDE FLIGHT processing

**sot/mica:** 4.21.1 -> 4.21.2 (4.21.1 -> 4.21.2)
  - [PR 221](https://github.com/sot/mica/pull/221): Recast dark cal image to native byte order
  - [PR 222](https://github.com/sot/mica/pull/222): Change sybase skip test to check for more restrictive vv creds
  - [PR 223](https://github.com/sot/mica/pull/223): Use github token authentication in workflow

**sot/Ska.arc5gl:** 3.1.3 -> 3.1.4 (3.1.3 -> 3.1.4)
  - [PR 8](https://github.com/sot/Ska.arc5gl/pull/8): Setting up automated builds
  - [PR 7](https://github.com/sot/Ska.arc5gl/pull/7): Make namespace package native

**sot/Ska.astro:** 3.2.3 -> 3.2.4 (3.2.3 -> 3.2.4)
  - [PR 8](https://github.com/sot/Ska.astro/pull/8): Setting up automated builds
  - [PR 7](https://github.com/sot/Ska.astro/pull/7): Make namespace package native

**sot/Ska.DBI:** 4.0.1 -> 4.0.2 (4.0.1 -> 4.0.2)
  - [PR 15](https://github.com/sot/Ska.DBI/pull/15): Setting up automated builds
  - [PR 16](https://github.com/sot/Ska.DBI/pull/16): Fix / improve tests to run on Windows
  - [PR 14](https://github.com/sot/Ska.DBI/pull/14): Make namespace package native

**sot/Ska.File:** 3.4.3 -> 3.4.4 (3.4.3 -> 3.4.4)
  - [PR 9](https://github.com/sot/Ska.File/pull/9): Setting up automated builds
  - [PR 8](https://github.com/sot/Ska.File/pull/8): Make namespace package native

**sot/Ska.ftp:** 3.5.2 -> 3.5.3 (3.5.2 -> 3.5.3)
  - [PR 19](https://github.com/sot/Ska.ftp/pull/19): Setting up automated builds
  - [PR 20](https://github.com/sot/Ska.ftp/pull/20): Windows compatibility
  - [PR 18](https://github.com/sot/Ska.ftp/pull/18): Make namespace package native

**sot/Ska.Matplotlib:** 3.11.3 -> 3.11.4 (3.11.3 -> 3.11.4)
  - [PR 12](https://github.com/sot/Ska.Matplotlib/pull/12): Setting up automated builds
  - [PR 11](https://github.com/sot/Ska.Matplotlib/pull/11): Make namespace package native

**sot/Ska.Numpy:** 3.8.2 -> 3.8.4 (3.8.2 -> 3.8.3 -> 3.8.4)
  - [PR 5](https://github.com/sot/Ska.Numpy/pull/5): Setting up automated builds
  - [PR 4](https://github.com/sot/Ska.Numpy/pull/4): Make namespace package native
  - [PR 6](https://github.com/sot/Ska.Numpy/pull/6): Fix the location of the C extension

**sot/Ska.ParseCM:** 3.3.3 -> 3.3.4 (3.3.3 -> 3.3.4)
  - [PR 7](https://github.com/sot/Ska.ParseCM/pull/7): Setting up automated builds
  - [PR 6](https://github.com/sot/Ska.ParseCM/pull/6): Make namespace package native

**sot/Ska.quatutil:** 3.3.2 -> 3.3.3 (3.3.2 -> 3.3.3)
  - [PR 9](https://github.com/sot/Ska.quatutil/pull/9): Setting up automated builds
  - [PR 8](https://github.com/sot/Ska.quatutil/pull/8): Make namespace package native

**sot/Ska.Shell:** 3.4.0 -> 3.4.1 (3.4.0 -> 3.4.1)
  - [PR 17](https://github.com/sot/Ska.Shell/pull/17): Setting up automated builds
  - [PR 18](https://github.com/sot/Ska.Shell/pull/18): Skip all tests on Windows
  - [PR 16](https://github.com/sot/Ska.Shell/pull/16): Make namespace package native

**sot/Ska.Sun:** 3.5.2 -> 3.5.3 (3.5.2 -> 3.5.3)
  - [PR 11](https://github.com/sot/Ska.Sun/pull/11): Setting up automated builds
  - [PR 10](https://github.com/sot/Ska.Sun/pull/10): Make namespace package native

**sot/Ska.tdb:** 3.5.2 -> 3.5.3 (3.5.2 -> 3.5.3)
  - [PR 11](https://github.com/sot/Ska.tdb/pull/11): Setting up automated builds
  - [PR 10](https://github.com/sot/Ska.tdb/pull/10): Make namespace package native

**sot/ska_helpers:** 0.1.0 -> 0.1.1 (0.1.0 -> 0.1.1)
  - [PR 9](https://github.com/sot/ska_helpers/pull/9): Setting up automated builds
  - [PR 10](https://github.com/sot/ska_helpers/pull/10): when running testr, avoid emitting this warning

**sot/starcheck:** 13.5.1 -> 13.6.0 (13.5.1 -> 13.6.0)
  - [PR 339](https://github.com/sot/starcheck/pull/339): Setting up automated builds
  - [PR 342](https://github.com/sot/starcheck/pull/342): Update ccd red/yellow limits for Apr2020 increase
  - [PR 343](https://github.com/sot/starcheck/pull/343): Use chandra_aca's guide_count for the perigee bright star check
  - [PR 344](https://github.com/sot/starcheck/pull/344): Use RLTT and schedule_stop in thermal calculation

# Testing

```
**************************************************************
***      Package                  Script            Status ***
*** ------------------ ---------------------------- ------ ***
***   Chandra.Maneuver                 test_unit.py   pass ***
***   Chandra.Maneuver           post_check_logs.py   pass ***
***       Chandra.Time                 test_unit.py   pass ***
***       Chandra.Time           post_check_logs.py   pass ***
*** Chandra.cmd_states                 test_unit.py   pass ***
*** Chandra.cmd_states           post_check_logs.py   pass ***
***         Quaternion                 test_unit.py   pass ***
***         Quaternion           post_check_logs.py   pass ***
***            Ska.DBI                 test_unit.py   pass ***
***            Ska.DBI           post_check_logs.py   pass ***
***          Ska.Numpy                 test_unit.py   pass ***
***          Ska.Numpy           post_check_logs.py   pass ***
***        Ska.ParseCM             test_unit_git.sh   pass ***
***        Ska.ParseCM           post_check_logs.py   pass ***
***          Ska.Shell                 test_unit.py   pass ***
***          Ska.Shell           post_check_logs.py   pass ***
***          Ska.Table             test_unit_git.sh   ---- ***
***          Ska.Table           post_check_logs.py   ---- ***
***     Ska.engarchive    test_make_archive_long.sh   ---- ***
***     Ska.engarchive                 test_unit.py   FAIL ***
***     Ska.engarchive           post_check_logs.py   FAIL ***
***            Ska.ftp                 test_unit.py   pass ***
***            Ska.ftp           post_check_logs.py   pass ***
***       Ska.quatutil             test_unit_git.sh   pass ***
***       Ska.quatutil           post_check_logs.py   pass ***
***            Ska.tdb                 test_unit.py   pass ***
***            Ska.tdb           post_check_logs.py   pass ***
***          acis_taco                 test_unit.py   pass ***
***          acis_taco           post_check_logs.py   pass ***
***       acisfp_check              test_regress.sh   pass ***
***       acisfp_check         test_regress_head.sh   pass ***
***       acisfp_check           post_check_logs.py   pass ***
***       acisfp_check              post_regress.py   pass ***
***       acisfp_check         post_regress_head.py   pass ***
***              agasc                 test_unit.py   pass ***
***              agasc           post_check_logs.py   pass ***
***              annie                 test_unit.py   pass ***
***              annie           post_check_logs.py   pass ***
***        chandra_aca                 test_unit.py   pass ***
***        chandra_aca           post_check_logs.py   pass ***
***            cxotime                 test_unit.py   pass ***
***            cxotime           post_check_logs.py   pass ***
***          dea_check              test_regress.sh   pass ***
***          dea_check         test_regress_head.sh   pass ***
***          dea_check           post_check_logs.py   pass ***
***          dea_check              post_regress.py   pass ***
***          dea_check         post_regress_head.py   pass ***
***          dpa_check              test_regress.sh   pass ***
***          dpa_check         test_regress_head.sh   pass ***
***          dpa_check           post_check_logs.py   pass ***
***          dpa_check              post_regress.py   pass ***
***          dpa_check         post_regress_head.py   pass ***
***               kadi         test_regress_long.sh   ---- ***
***               kadi                 test_unit.py   pass ***
***               kadi           post_check_logs.py   pass ***
***               kadi         post_regress_long.py   ---- ***
***              maude                 test_unit.py   pass ***
***              maude           post_check_logs.py   pass ***
***               mica                 test_unit.py   pass ***
***               mica           post_check_logs.py   pass ***
***   package_manifest              test_regress.sh   pass ***
***   package_manifest           post_check_logs.py   pass ***
***   package_manifest              post_regress.py   pass ***
***           parse_cm                 test_unit.py   pass ***
***           parse_cm           post_check_logs.py   pass ***
***            proseco                 test_unit.py   pass ***
***            proseco           post_check_logs.py   pass ***
***         psmc_check              test_regress.sh   pass ***
***         psmc_check         test_regress_head.sh   pass ***
***         psmc_check           post_check_logs.py   pass ***
***         psmc_check              post_regress.py   pass ***
***         psmc_check         post_regress_head.py   pass ***
***             pyyaks                 test_unit.py   pass ***
***             pyyaks           post_check_logs.py   pass ***
***           sparkles                 test_unit.py   pass ***
***           sparkles           post_check_logs.py   pass ***
***          starcheck              test_regress.sh   pass ***
***          starcheck           post_check_logs.py   pass ***
***          starcheck              post_regress.py   pass ***
***          timelines test_unit_git_sybase_long.sh   ---- ***
***          timelines           post_check_logs.py   ---- ***
***               xija                 test_unit.py   pass ***
***               xija           post_check_logs.py   pass ***
**************************************************************
```
# Related Issues

Fixes #371
Fixes #376
Fixes #377
Fixes #353
Fixes #375
Fixes #354
Fixes #355
Fixes #361
Fixes #362
Fixes #364
Fixes #365
Fixes #366
Fixes #368
Fixes #369
Fixes #359
Fixes #360
Fixes #363
Fixes #367
Fixes #370
Fixes #356
Fixes #357
Fixes #358
Fixes #381

### CODE REVIEW

**Comment by jeanconn** [comment]
If the testing is looking good, looks like we just need to finish up the description of the changes and get a notice out.  For the summary, my impression is that the highlights are 

   * native namespace transition (with a brief explanation of why we've done this)
   * starcheck updates to
      * work better with the April ACA CCD limit increase
      * support RLTT and schedule stop
   * kadi commands-related updates to
      * support the starcheck RLTT and schedule stop change
      * add support for ACIS FP state
   * eng_archive update to support computed msids

This comment can be deleted when the top matter is finalized.

**Comment by jeanconn** [comment]
I assume the eng archive testing is still failing the same way it was failing in ska3 flight?

**Comment by javierggt** [comment]
There is also:
- Documentation for acis_thermal_check

**Comment by jeanconn** [comment]
Right, since that already got briefed at a LR by ACIS, it might not need summary special attention?  But up to you.

**Comment by jeanconn** [comment]
Looks like there is a 2020.5 reference that should be 2020.6 in the deployment, and should explain the test FAIL but besides that looks good.

**Pull request merged**
