### PR TITLE
Release 2020.1

### LINKED ISSUE #224: Update find_attitude to 3.2.1
Initial Python 3 compatible release:
https://github.com/sot/find_attitude/releases/tag/3.2

### LINKED ISSUE #229: Update kadi to 4.19
Update to version 4.19:

https://github.com/sot/kadi/pull/139 : Update_cmds fixes for py3
https://github.com/sot/kadi/pull/138 : Fix ingest of non-load commands during a load stoppage (anomaly)
https://github.com/sot/kadi/pull/146 : Migrate update_cmds task_schedule to ska3 idiom
https://github.com/sot/kadi/pull/147 : Update mid-manvr test to use column comparisons and isclose
https://github.com/sot/kadi/pull/152 : Add ACIS raw-mode SI modes to ACIS states 
https://github.com/sot/kadi/pull/143 : Py3 server with + event/cmd cron jobs processing with django 3.0

Highlights of 143:
- Make the django server run with Python 3 and django 3.0
- Make the events update work on Python 3
- Add `obsid` as a standard field for telemetry-based events
- Change name of event database file from `events.db3` to `events3.db3`.  New file and schema are not compatible with previous version.
- Flake8 changes

### LINKED ISSUE #232: Remove spyder from installed packages
Spyder is lousy and never really worked anyway.  This is mostly for `shiny` but could happen any time.

### LINKED ISSUE #238: Update django to 3.0.x
Kadi 4.19 requires django 3.0+

### LINKED ISSUE #239: Update sherpa to 4.11 on MacOS
On my mac running catalina, I installed sherpa 4.9.1 using `-c $ska3conda` and doing `import sherpa.ui` gave a segfault.  Installing sherpa from the sherpa channel `-c sherpa` gave version 4.11 plus a couple of new libraries, and this worked:
```
The following NEW packages will be INSTALLED:

    libcxx:    4.0.1-hcfea43d_1            
    libcxxabi: 4.0.1-hcfea43d_1            
    sherpa:    4.11.1-py36h0a44026_0 sherpa
```
Not sure about High Sierra, but maybe we should update the tarballs on our channel for Mac?  Shiny branch should maybe update to 4.11 for mac and linux?

### LINKED ISSUE #243: Update ska_sync to 4.6
sot/ska_sync#15 Add kadi/events3.db3, remove eng_archive in favor of cheta_sync

### LINKED ISSUE #245: Update mica to 4.19.1
sot/mica#213 
- Small fix for PCAD table generation to work with django 3.0a

### LINKED ISSUE #246: Add ska_helpers 0.2
Initial version of ska_helpers that includes:
- Support for SCM versioning of packages
- Utility functions for getting or logging run time information such as user, machine, version

### LINKED ISSUE #247: Update agasc to 4.8
https://github.com/sot/agasc/pull/40 : Add get_stars() function to get multiple ids / dates
https://github.com/sot/agasc/pull/38 : Make proseco-optimized AGASC file (no impact to installed library)

### LINKED ISSUE #249: Update Chandra.Time to 3.20.4
https://github.com/sot/Chandra.Time/pull/34 : Add compile arg for building on MacOS Catalina / Xcode 11.2

### LINKED ISSUE #250: Update sparkles to 4.4
https://github.com/sot/sparkles/pull/126 : PEP8 / flake8 fixes
https://github.com/sot/sparkles/pull/127 : Add GitHub action for flake8 checking
https://github.com/sot/sparkles/pull/128 : One more PEP8 that slipped through
https://github.com/sot/sparkles/pull/130 : Add --open-html option to open HTML in browser

### LINKED ISSUE #251: Update Chandra.Maneuver to 3.7.2
https://github.com/sot/Chandra.Maneuver/pull/14 : Cast number of steps to int (fix test warning)

### LINKED ISSUE #252: Update task_schedule to 4.2
https://github.com/sot/task_schedule/pull/15 : Initial steps to modernizing task_schedule

### LINKED ISSUE #253: Update watch_cron_logs to 4.2
https://github.com/sot/watch_cron_logs/pull/6 : Modernize watch_cron_logs

### LINKED ISSUE #255: Chandra.Time won't conda build in master
```
aca-presto% python ska_builder.py --build-root /export/aca/test-django/ Chandra.Time                       - Building package Chandra.Time.
  - Cloning or updating source source Chandra.Time.
  - Updated repo in /export/aca/test-django/src/Chandra.Time
  - Auto-checked out at 3.20.4 which is also tip of master
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'
  - SKA_PKG_VERSION=
```

Looks like I need maybe need cython in the builder environment to make this work?

### PR DESCRIPTION
**Pull request by jeanconn**
## Release Notes

The 2020.1 skare3 release is significant in that it includes substantive changes to a few packages and includes setuptools_scm modernization of most of our Python modules.

### Package Updates

**[acis_taco](https://github.com/sot/acis_taco/releases/tag/4.1.0)**
 - [x] https://github.com/sot/acis_taco/pull/13 Allow specifying p_earth_body in call to calc_earth_vis
    - This code was used to make the xija file in flight use, but an updated acis_taco was not installed at that time

**[agasc](https://github.com/sot/agasc/releases/tag/4.8.0)**
- [x] https://github.com/sot/agasc/pull/40 Add get_stars() function to get multiple ids / dates

**[annie](https://github.com/sot/annie/releases/tag/0.9.1)**
  - [x] https://github.com/sot/annie/pull/96 Add bgd init value to track_stars_setup

**[Chandra.Maneuver](https://github.com/sot/Chandra.Maneuver/releases/tag/3.7.2)**
- [x] https://github.com/sot/Chandra.Maneuver/pull/14 Cast number of steps to int

**[Chandra.Time](https://github.com/sot/Chandra.Time/releases/tag/3.20.4)**
- [x] https://github.com/sot/Chandra.Time/pull/34 Add compile arg for building on MacOS Catalina / Xcode 11.2

**[find_attitude](https://github.com/sot/find_attitude/releases/tag/3.3.2)**
- [x] https://github.com/sot/find_attitude/pull/7 Changes to go along with the py3-server kadi branch
  - Mostly just a change in a module name.  Django 3.0 requires web apps to have a unique name as determined by the module name.

**[kadi](https://github.com/sot/kadi/releases/tag/5.0.0)**
- [x] https://github.com/sot/kadi/pull/152 Add ACIS raw-mode SI modes to ACIS states 
- [x] https://github.com/sot/kadi/pull/143 Py3 server with + event/cmd cron jobs processing with django 3.0
   - **Interface impacts**:  Makes and uses new, not-back-compatible events3.db3
   - Make the django server run with Python 3 and django 3.0
   - Make the events update work on Python 3
   - Add `obsid` as a standard field for telemetry-based events
   - Change name of event database file from `events.db3` to `events3.db3`.  New file and schema are not compatible with previous version.
   - Flake8 changes

**[mica](https://github.com/sot/mica/releases/tag/4.20.0)**
- [x] https://github.com/sot/mica/pull/213 Small fix for PCAD table generation + SCM version changes
  - Tiny one-line change in the way kadi.events are imported required by django 3.0

**[ska_helpers](https://github.com/sot/ska_helpers/releases/tag/0.1.0)**
- [x] [Initial Release 0.1.0](https://github.com/sot/ska_helpers/releases/tag/0.1.0)
   - This new package includes a module `version.py` that provides functionality for getting a package version using either distribution metadata or git tag and commit data.
   - Also includes convenience methods to get and/or log runtime information like user, machine name etc for scripts.

**[ska.quatutil](https://github.com/sot/Ska.quatutil/releases/tag/3.3.2)**
 - [x] PR #7: Refactor test

**[ska_sync](https://github.com/sot/ska_sync/releases/tag/4.6.0)**
- [x] https://github.com/sot/ska_sync/pull/15 Add kadi/events3.db3, remove eng_archive in favor of cheta_sync
  - Interface changes: Changes the default files that are synced with the tool if user creates new working sync config

**[Ska.Shell](https://github.com/sot/Ska.Shell/releases/tag/3.4.0)**
- [x] https://github.com/sot/Ska.Shell/pull/15 Fix bash support on catalina + modernize
  - Fix a problem that came up because Mac catalina outputs some cruft when you start a bash shell.
  - Also removes Python 2.7 support.

**[sparkles](https://github.com/sot/sparkles/releases/tag/4.4.0)**
- [x] https://github.com/sot/sparkles/pull/130 Add --open-html option to open HTML in browser
- [x] https://github.com/sot/sparkles/pull/131 Add check that guide star is a valid guide candidate

**[task_schedule](https://github.com/sot/task_schedule/releases/tag/4.2)**
- [x] https://github.com/sot/task_schedule/pull/15 Initial steps to modernizing task_schedule

**[watch_cron_logs](https://github.com/sot/watch_cron_logs/releases/tag/4.2)**
- [x] https://github.com/sot/watch_cron_logs/pull/6 Modernize

**[xija](https://github.com/sot/xija/releases/tag/4.16.0)**
 - [x] https://github.com/sot/xija/pull/48 Allow the timestep to be set from the model specification

**Includes just package changes for setuptools-scm**
- acdc, chandra_aca, Chandra.cmd_states, cxotime, hopper, maude, parse_cm, proseco, pyyaks, Ska.arc5gl, Ska.astro, Ska.DBI, Ska.File, Ska.Numpy, Ska.Matplotlib, Ska.ParseCM, Ska.tdb, starcheck, tables3_api, testr

**ACIS packages with changes for setuptools-scm**
- acis_thermal_check, acisfp_check, backstop_history, dea_check, dpa_check, psmc_check

**Updates to core/not-ska packages**
 - [x] setuptools_scm 3.3.3
 - [x] django 3.0.1
 - [x] sherpa to 4.11.1 on OSX

The spyder package has been removed from ska3-core
  - [x] Remove spyder

### Interface impacts

The package interface impacts are called out above (kadi and ska_sync).

xija has back-compatible API changes.  xija allows models to specify timestep from the spec (but uses the default of 328 seconds for back-compatibility). 

### Review

All changes have been reviewed by the aspect team.

### Testing

The updated set of modules pass unit and integration testing.  In addition, the more involved testing for the kadi+django update was documented by Tom in [kadi PR 143](https://github.com/sot/kadi/pull/143

### Promotion

After approval, updated ska3-flight and ska3-perl will be installed on HEAD and GRETA ska3/flight.

The kadi package update will require minor updates to the kadi cron jobs.

The removal of spyder from the ska3-core package does not require that it be removed from HEAD/GRETA ska3/flight , though we do believe that no one is actually using the package.

### Github

Closes #255 
Closes #253 
Closes #252 
Closes #251 
Closes #250 
Closes #249 
Closes #247 
Closes #246 
Closes #245 
Closes #243 
Closes #239 
Closes #238 
Closes #229
Closes #224 
Closes #232 

---

### CODE REVIEW

**Comment by jeanconn** [comment]
I've updated the PR text with more content intended for external review (LR).  If you have any comments or edits @taldcroft  and @javierggt , please feel free.

**Comment by jeanconn** [comment]
The skare3 changes up through ba6cc13 correspond to the packages that are built and in ska3-conda and ska3-conda/test (ska3-flight pkg only) repos right now.   This could go as a release if we run out of time before LR this week to do the rest.

**Comment by taldcroft** [comment]
With the effort of integration testing and deploy, I'm fine with waiting another week and just doing one release.

**Comment by taldcroft** [comment]
@javierggt - to close this out can you find someplace in the [maintainer wiki](https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-maintainers) to capture the versioning policy and edit accordingly.  I note there are already things in there that are wrong with SCM versioning, for instance :

*8. If necessary, do a quick PR to update the package version number. This is required if the current version in the code is the same as the last release tag.*

**Comment by jeanconn** [comment]
Regarding effort; I had already done the regression testing (ska_testr) on this set of package versions, but fine to defer overall for deploy effort as well (depending on how things move).

**Comment by jeanconn** [comment]
Silly question, but what order should we use in the PR notes for the package updates?  I think I started with "big" to "little" in substantive changes, but now it is just a mess.

**Comment by taldcroft** [comment]
Doesn't matter to me...

**Comment by jeanconn** [comment]
I think we'll need to fix https://github.com/sot/ska_helpers/issues/7  (assuming it isn't some bizarre building or setup issue in my test environment) before promoting this.

**Comment by jeanconn** [comment]
I've pulled Quaternion and am running the integration tests with the new ACIS packages.

**Pull request merged**
