### PR TITLE
git clone with https instead of ssh

### PR DESCRIPTION
**Pull request by javierggt**
Some of the red in the dashboard comes from this.

Automated build uses only basic authentication over https. I did not include ssh keys for the build process. For this reason, I would replace all uses of git@github.com: for the https url.

There are other possible solutions, I just chose the simplest one:
- add ssh keys
- make it an option of the script.

### CODE REVIEW

**Comment by javierggt** [comment]
I just added an option to either use https or ssh. It either uses ssh or https on all packages (right now some packages have https or ssh, and one usually has a preferred authentication method).

**Comment by javierggt** [comment]
Is that an official approval? :-)

I did test that by default annie/Quaternion was fetched using ssh and with the option it used https. They are examples of meta.yaml hacing ssh/https respectively.

**Comment by jeanconn** [comment]
Eh.  I hit the "approve" button when I commented, so that's official.  Overall I don't think we need a super-high bar on changes to ska_builder.py as there aren't really credible paths by which we'll build a package "incorrectly" with these kinds of changes.

**Comment by taldcroft** [comment]
BTW, my current practice is to delete PR branches immediately upon merge to keep things tidy.  Is there a reason to not do that?

**Comment by javierggt** [comment]
no, no reason. It should be deleted.

**Pull request merged**
