### PR TITLE
Add simple meta/recipe for chandra_limits

### PR DESCRIPTION
**Pull request by jeanconn**
Add simple meta/recipe for chandra_limits.  

I figured this could be tested with https://github.com/sot/chandra_limits/pull/1 , though I have not done so.  And https://github.com/sot/chandra_limits/pull/1 would still need the workflows for the actions for this to do something on merge.

### CODE REVIEW

**Comment by jzuhone** [comment]
@jeanconn @javierggt let me know what I need to add re: workflows and I can do it. it's not an acisops package per se, so it probably needs whatever standard workflows sot has (if they are different at all).

**Comment by jeanconn** [comment]
Thanks @jzuhone !  I think the updated workflows I stuck in https://github.com/jzuhone/chandra_limits/pull/1 might do it but @javierggt is more expert.

**Comment by jeanconn** [comment]
Yes, I wasn't sure if anything used the "org" to determine this or if it was just the workflow selection.  I think in this case we do want a new package def / recipe in sot/skare3 (which is this PR) and have the workflows in sot/chandra_limits reference it.

**Comment by jeanconn** [comment]
I don't see an easy way to test this against the dev branch, so I suggest just merging and forward and fix as needed.

**Review by javierggt — APPROVED** [review]

**Comment by jzuhone** [comment]
@jeanconn @javierggt we have a first release of `chandra_limits`: https://github.com/sot/chandra_limits/releases/tag/0.5.0

**Comment by jeanconn** [comment]
Thanks @jzuhone!  With the release, a conda package was successfully built and put in the test channel.  So, a few questions:

1) Does chandra_limits need to be a private repo?
2) What is the plan with management of it?  Does it belong in ska3-flight as something that we update with regular ska3-flight releases?
3) Not really a question but looks like it is still failing ruff and black in the release.

**Comment by jzuhone** [comment]
Hi @jeanconn,

> 1. Does chandra_limits need to be a private repo?

No, I don't think so. I wasn't even aware that it was. @matthewdahmer can you comment? 

> 2. What is the plan with management of it? Does it belong in ska3-flight as something that we update with regular ska3-flight releases?

Yes, it needs to go in ska3-flight, as `acis_thermal_check` (among other things) are going to depend on it. 

> 3. Not really a question but looks like it is still failing ruff and black in the release.

Yes, I plan on addressing this soon.

**Pull request merged**
