### PR TITLE
Add recipe for prompt-toolkit

### PR DESCRIPTION
**Pull request by taldcroft**
This allows making a local build of 2.0.10 which fixes problems on Windows.

### CODE REVIEW

**Comment by jeanconn** [comment]
Sorry you had to cross over to the dark side.

**Comment by jeanconn** [comment]
What was the prompt-toolkit issue and is it likely to get fixed upstream?

**Comment by taldcroft** [comment]
Oh dear, not a clue.

**Comment by taldcroft** [comment]
Bad Tom for not providing a better trail of crumbs.

**Comment by jeanconn** [comment]
No sweat, I was just noticing that we're handling sherpa and prompt-toolkit with this special handing... and while phasing out the sherpa special handling also wondered if there could come a time when this could go.  But I'd also guess there isn't rapid development on this package and it is unlikely to hold us back for a while (as other "core" packages advance).

**Pull request merged**
