### PR TITLE
2024.5

### LINKED ISSUE #1351: Release ska3-flight 2024.5
# Packages to include

- List package name+version or github issue number

### Package and Test

- [x] Create branch named {version}-branch
- [x] Create PR titled {version} from {version}-branch into master
- [x] Create a pre-release `{version}rc{N}` at the latest commit in the branch
- [x] Check packages are built and automated tests pass.
- [x] Promote packages from `masters` to `test` conda channel (`skare3-promote --to test ...`).
- [x] List in PR any data products that need to be promoted to $SKA/data (check PR's interface impacts).
- [x] Install on HEAD and GRETA Linux test environments (`ska3/test`).
- [x] Confirm that test data (SKA/data) is appropriate for release testing (any custom test data is set or previous test data cleaned out)
- [x] Run testr on HEAD and GRETA
- [x] Add related issues to PR (`skare3-milestone-issues ...`).
- [x] Document all changes (`skare3-changes-summary ...`).
- [x] Write summary + highlight relevant changes.
- [x] Document test results (`skare3-test-dashboard -b -i outputs/logs/last && rsync -av outputs/logs/last/ proj/sot/ska/www/skare3/testr/releases/2024.5-HEAD`).
- [x] Create FSDS Jira ticket and wait for approval.

### Promote:
- [x] Promote packages to `flight` conda channel (`skare3-promote ...`).
- [x] Announce to aca@cfa/slack.
- [x] Update ska3/flight on HEAD as aca user.
- [x] Update ska3/flight on GRETA as SOT user.
- [x] Promote any data products listed in PR to be promoted.
- [ ] Run ska_testr on HEAD and GRETA.
- [ ] Document test results (`skare3-test-dashboard ...`).
- [x] Announce to aca@cfa/slack.
- [x] Announce to sot@cfa and fot@ipa.
- [ ] Merge PR.

### PR DESCRIPTION
**Pull request by javierggt**
# ska3-flight 2024.5

This PR includes:
- updates to chandra_limits to support new ACIS FP limits
- update to the time range used for High IR Zone checking in starcheck

Note: **This PR includes an ARM build for the first time - that build is intended for beta testing and not operational use **

Closes #1351 

## Interface Impacts:

**chandra_limits** : new limits from chandra_models 3.53 are used by the ACIS FP model.  Requires chandra_models >= 3.53.

**parse_cm**: new `required_sequenced_duration` added to or_list_types.yaml (no impact)

**xija**: Colors of the new ACIS FP limits in xija_gui_fit and acis_thermal_check will change.

**starcheck**: Changes to placement of newlines in the text file report.

## Testing:

- [Automated tests](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/2024.5rc4/).

skare3 dashboard and test result password at https://icxc.cfa.harvard.edu/aspect/skare3_dash_cred.txt

The latest release candidates will be installed in `/proj/sot/ska3/test` on HEAD, and all release candidates will be available for testing from the usual channels:
```
conda create -n ska3-flight-2024.5rc4 --override-channels \
  -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight \
  -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/test \
  ska3-flight==2024.5rc4
```

## Review

All operations critical or impacting PR's are independently and carefully reviewed. For other PR's the level of detail for review is calibrated to operations criticality. Some PR's that are confined to aspect-team-specific processing may have little to no independent review.

## Deployment

ska3-flight 2024.5 will be promoted to flight conda channel and installed on HEAD and GRETA Linux upon approval of FSDS Jira ticket and at/after promotion of chandra_models 3.53 .

# Code changes

### Updated Packages

- **acispy:** 2.5.0 -> 2.6.0
   - PR https://github.com/acisops/acispy/pull/12
- **acis_thermal_check:** 5.1.0 -> 5.1.1
   - PR https://github.com/acisops/acis_thermal_check/pull/74 
- **agasc:** 4.18.3 -> 4.19.0
   - PR https://github.com/sot/agasc/pull/177
   - PR https://github.com/sot/agasc/pull/173
   - PR https://github.com/sot/agasc/pull/175
- **chandra_limits:** 0.8.0 -> 0.9.1
   - PR https://github.com/sot/chandra_limits/pull/16
   - PR https://github.com/sot/chandra_limits/pull/15
- **kadi:** 7.10.0 -> 7.10.1
   - PR https://github.com/sot/kadi/pull/331
- **parse_cm:** 3.14.3 -> 3.15.0
   - PR https://github.com/sot/parse_cm/pull/52
- **proseco:** 5.13.0 -> 5.13.1
   - PR https://github.com/sot/proseco/pull/397
- **starcheck:** 14.8.1 -> 14.9.0
   - PR https://github.com/sot/starcheck/pull/442
   - PR https://github.com/sot/starcheck/pull/441
- **xija:** 4.31.3 -> 4.32.0
   - PR https://github.com/sot/xija/pull/139
   - PR https://github.com/sot/xija/pull/138

# Related Issues

### CODE REVIEW

**Comment by taldcroft** [comment]
FWIW I confirmed that `xija_gui_fit` runs as expected on MacOS ARM. I did basic operations of displaying plots, bringing up a histogram and doing a fit of some parameters. The latter validates that `sherpa` is working as expected.

**Comment by jeanconn** [comment]
Do you have a functional test we should run for the *other* platforms?

**Comment by taldcroft** [comment]
For `xija` the functional test is roughly:
```
xija_gui_fit dpa --days 200
```

- Bring up the histogram of residuals.
- Select about 10 of the `solarheat__dpa0__P..` parameters for fitting and hit the Fit button.
- Confirm that the fit improved and nothing weird happened.

For `aca_view` I just looked at a random one-hour chunk of telemetry in the last year.

**Comment by jeanconn** [comment]
I reverted the sherpa update in the now-building rc because it looks like the sherpa 4.16 in current channels needs ciao and I wasn't clear on its status.
```
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides ciao >=4.16.0,<4.16.1.0a0 needed by sherpa-4.16.0-py[31](https://github.com/sot/skare3/actions/runs/9131183444/job/25110083103#step:3:32)1h3fd9d12_0

Could not solve for environment specs
The following package could not be installed
└─ ska3-flight 2024.5rc1  is not installable because it requires
   └─ ska3-core 2024.5rc1 , which requires
      └─ sherpa 4.16 , which requires
         └─ ciao >=4.16.0,<4.16.1.0a0 , which does not exist (perhaps a missing channel).
```

**Pull request merged**
