### PR TITLE
Update ska3-matlab in bulk for 2019_210

### PR DESCRIPTION
**Pull request by jeanconn**
Includes these pkg updates
- acisfp_check v2.7.0
- acis_thermal_check v2.9.0
- chandra_aca 4.27
- chandra.cmd_states 3.15
- dea_check v2.3.0
- dpa_check v2.4.0
- kadi 4.18.1
- mica 4.19
- parse_cm 3.5
- proseco 4.7.1
- pyyaks 4.4
- ska.dbi 4.0
- ska.engarchive 4.47.3
- ska.ftp 3.5.1
- ska.shell 3.3.4
- ska_sync 4.5
- testr 4.3

adds pkgs
- setuptools_scm (added in ska3-core update which is not visible in the diff)
- acdc 4.3.1
- starcheck 13.5
- annie 0.8.2

### CODE REVIEW

**Comment by taldcroft** [comment]
What about annie?  Baski expressed some mild interest.

Eng_archive to 4.47.3?  This is not a complete no-op for MATLAB, since truncating the archive has been advertised at the cheta sync tutorial.

**Comment by jeanconn** [comment]
OK, so this is a draft and feedback is good.  

Yesterday you said don't bother to eng_archive 4.47.3; fine to add it.

Also fine to add back in annie but we seem to have trouble cutting releases.

**Comment by jeanconn** [comment]
Also in the running:

- testr
- Ska.Shell

**Comment by taldcroft** [comment]
Sure.  I would just sync things up.

**Comment by taldcroft** [comment]
> Yesterday you said don't bother to eng_archive 4.47.3; fine to add it.

That was shortsighted on my part, both because there actually *is* a reason (that I just thought of), and more because the new policy is basically to not require a reason to sync up, but instead default to bringing all the MATLAB versions up to the very latest in flight.

**Comment by jeanconn** [comment]
Do you mean not release any new packages for this?  There are some tiny updates in open or merged prs that I thought might make sense to just get done.

**Comment by jeanconn** [comment]
Well and 4.47.3 isn't in flight yet so policy fuzzy

**Comment by taldcroft** [comment]
> Do you mean not release any new packages for this? There are some tiny updates in open or merged prs that I thought might make sense to just get done.

Specific examples would help out since this is news to me, but in general it seems fine.  I would say to make the corresponding change(s) to ska3-flight/meta in master at the same time.  I.e. make a separate PR to put in the new package to ska3-flight and milestone the PR with `2019-12`.

**Comment by jeanconn** [comment]
Specific examples include starcheck, Ska.eng_archive, annie, testr, and Ska.Shell with open and merged PRs that I tried to draw to your attention this morning via github.

Honestly, it would be nice to get Quaternion, chandra_aca, and maude in too, but that seems a reach.

**Comment by taldcroft** [comment]
Just for kicks I did a conda install of Ska.Shell to my Windows Ska3.  It installs and imports, but tests, no so much:
```
In [1]: import Ska.Shell

In [2]: Ska.Shell.test()
================================================= test session starts =================================================
platform win32 -- Python 3.6.9, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\aldcroft\Miniconda3\envs\ska3\lib\site-packages\Ska.Shell-3.3.3-py3.6.egg
collected 20 items

Ska\Shell\tests\test_shell.py F.FFFFFFFFFFFFFFFFFF                                                               [100%]
```
Eventually if we have a Windows skare3 distribution then this would probably not be included for Windows.

**Comment by jeanconn** [comment]
This does not surprise me.

Also, is your vm 32 bit?

**Comment by taldcroft** [comment]
> Also, is your vm 32 bit?

64-bit Windows 10

**Comment by jeanconn** [comment]
OK, then should I be confused about "platform win32" in your pasted text?

**Comment by jeanconn** [comment]
I've just installed this in a test / dev ska on fido and I'm not immediately understanding this error importing kadi. SKA is just set to /proj/sot/ska .

```
(ska3mat) bash-4.1$ ipython
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import kadi.events
---------------------------------------------------------------------------
ImproperlyConfigured                      Traceback (most recent call last)
<ipython-input-1-08991e70577d> in <module>()
----> 1 import kadi.events

/fido.real/ska3dev/envs/ska3mat/lib/python3.6/site-packages/kadi/events/__init__.py in <module>()
     52 # https://docs.djangoproject.com/en/1.10/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage
     53 try:
---> 54     django.setup()
     55 except AttributeError:
     56     pass

/fido.real/ska3dev/envs/ska3mat/lib/python3.6/site-packages/django/__init__.py in setup(set_prefix)
     25             '/' if settings.FORCE_SCRIPT_NAME is None else force_text(settings.FORCE_SCRIPT_NAME)
     26         )
---> 27     apps.populate(settings.INSTALLED_APPS)

/fido.real/ska3dev/envs/ska3mat/lib/python3.6/site-packages/django/apps/registry.py in populate(self, installed_apps)
     87                     raise ImproperlyConfigured(
     88                         "Application labels aren't unique, "
---> 89                         "duplicates: %s" % app_config.label)
     90 
     91                 self.app_configs[app_config.label] = app_config

ImproperlyConfigured: Application labels aren't unique, duplicates: web

In [2]:    
```

**Comment by taldcroft** [comment]
> OK, then should I be confused about "platform win32" in your pasted text?

Perhaps.  But it's definitely 64-bit, from the label that VirtualBox gives to the VM down to `platform.architecture()` and `sys.maxsize`.  So maybe pytest just has a bug.

**Comment by jeanconn** [comment]
Ah.  I wonder if he kadi problem is from find_attitude.web or some such in this test area.  I conda removed find_attitude to check, but it looks like it is still registered with django (that seems like a bug).

**Comment by jeanconn** [comment]
For today's ska3-matlab freeze I think removing find_attitude is OK.  @taldcroft are we good to hand off this list of package updates and additions to Mark now?

**Comment by taldcroft** [comment]
Looks good to me.  For kicks I compared the ska3-matlab and ska3-flight distributions and got an expected result.  I just wonder now if all the packages in ska3-flight3 should be similarly updated in master or even in this PR.  (That doesn't affect handing off a version / package list to Mark).
```
(ska3-cheta) neptune$ diff pkg_defs/ska3{-flight,-matlab}/meta.yaml 
2,3c2,3
<   name: ska3-flight
<   version: 2019.11.15
---
>   name: ska3-matlab
>   version: 2019.11.20
16d15
<     - annie ==0.7
19a19
>     - annie ==0.8.2
34c34
<     - proseco ==4.6
---
>     - proseco ==4.7.1
41c41
<     - ska.engarchive ==4.47.2
---
>     - ska.engarchive ==4.47.3
50c50
<     - ska.shell ==3.3.3
---
>     - ska.shell ==3.3.4
54c54
<     - starcheck ==13.4
---
>     - starcheck ==13.5
56c56
<     - testr ==3.2
---
>     - testr ==4.3
```

**Comment by jeanconn** [comment]
I agree on also updating ska3-flight, but I don't think it necessarily needs to get done in this PR.  Not going to miss that we want these updates, though I just opened a reminder issue.

**Comment by jeanconn** [comment]
Though it looks like ska.shell went missing in my top matter, so I'll update that even if it doesn't apply to windows.

**Comment by jeanconn** [comment]
This developed a conflict due the a find_attitude recipe in the branch.  I just rebased that recipe away.  ska3-matlab unchanged.

**Pull request merged**
